### ISSUE TITLE
More control over decal's shader and duplicating decal. 

### ISSUE THREAD

**Issue by warriormaster12** [Master-J/DecalCo#4]
Thank you for creating this addon, it is pretty good. I can already add some cool blood decals into my game but there are couple of things that bother me. 

The first issue that I found is that duplicating a decal doesn't seem to currently work since the duplicate decal is empty. It would make things easier, if I could just duplicate decals without any issues :D 

The second issue is (if I understood correctly) that custom shaders aren't currently supported. It would be really cool if this addon would take advantage of visual shaders since that can open up doors for more complex looking decals. 

Merry Christmas and happy New year !!

**Comment by Master-J** [comment]
Hi, thanks for the feedback.

The first issue should now be fixed thanks to #5 that just got merged into the master branch (update to the tutorial in the readme and godot's asset lib will come tomorrow).

As for the second point, you can now, also thanks to #5, tweak the shader's look by duplicating and editing the decal shader (then you'll have to make a material out of it and give it to a cube meshinstance). Keep in mind that the shader is quite complex by nature so changes can easily break it. I recommand only editing the parte where the shader writes to the albedo and emission.

Finally, i'm not too fond of using visual shaders for that, the graph it'd give would be really huge and complex, making it hard to understand (though i admit that shader code is often akin to black magic stuff). But if someone submits a PR with a working visual shader version, i will surely merge it.
